### ISSUE TITLE
Update contest model to allow "seatnum" = "none"

### ISSUE THREAD

**Issue by frankreporting** [SCPR/kpcc_backroom_handshakes#14]
Allow more than just integers. For instance: 
- For municipal at-large elections, there will be no seat number (i.e. no city council districts)
- For Assembly, Senate, etc., there will be district numbers
- For measures, there will be either non-integer codes or else None

**Comment by chrislkeller** [comment]
Currently the model allows for null and blank values.. Not sure what the issue is here.
