### ISSUE TITLE
Consider data validation and formatting conflicts and opportunties

### ISSUE THREAD

**Issue by frankreporting** [SCPR/kpcc_backroom_handshakes#16]
- [x] "Office" model may need to be more robust. For state level, we should have no conflicts, but when we have more than one county, offices like "Supervisor District 5" will start to conflict.
  - [x] Consider including county/municipality info in either slug or office name
- [x] Double check naming of offices between LAC and SoS to make sure we're the same
  - [x] Clash between LA County and SoS when creating House races
    - `us-house-of-representatives-district-26 created`
- [x] A reusable method creates:
  - [x] officeid
  - [x] contestid
  - [x] candidateid
  - [x] measureid
  - [x] judicialid
- [x] Change measure name to its prop # and move current name to description or a subtitle field
  - [x] Prop 50 would be an SoS measure. Measure J would be LAC measure
    - States give "Prop" numbers. Counties appear to give letters, maybe numbers in some cases, but usually prefaced "Measure." Whatever descriptor is given (i.e. "Suspension of legislator pay") should then be moved to a "description" field and not given as the "title" of the measure
- [x] Consider boolean flag for records that require attention?
- [x] Need to fix Courts of Appeal contest import? Appears to create a unique contest instance for every candidate
- [x] Test evaluates data type to determine if the data is realistic and reasonable given the election and/or race
- [x] Make sure ints and floats are being converted over where necessary

**Comment by chrislkeller** [comment]
Moving `If a user is updating a field in a record the record is locked` to #24. Attempted to implement and fell down a wormhole.
