### ISSUE TITLE
Standardize the officeID between SoS and LAC data

### ISSUE THREAD

**Issue by frankreporting** [SCPR/kpcc_backroom_handshakes#23]
- [x] Change LAC's "appellate-court-justices" to "courts-of-appeal" and district #
- [x] ~~Decide how to allow multiple "supreme court justice" offices (no district or seat numbers are given)~~ (see next item)
- [x] Drop Supreme Court "seat numbers" in SoS and make office/contest names just "Supreme Court" to match LAC
  - This will mean we're handling Supreme Court the same way we handle Courts of Appeal: there should be one office "Supreme Court" and one contest "Supreme Court" and each candidate appearing under that contest with yes/no %. Why? Because there are no seat numbers for Supreme Court, and there also don't appear to be seat numbers in a given Court of Appeal district - there are "divisions" but multiple justices can be in each division. 
- Also not sure you'll like how I did this. See line 153 in manager_sos_results.py
- [x] Fix LAC's "united-states-senator" to match "us-senate"
- [x] Drop result source from officeID, so no "lac" or "sos" prefix
- [x] Change Supreme Court officename in LAC to just "Supreme Court"

**Comment by frankreporting** [comment]
@chrislkeller I can tackle these this weekend

**Comment by frankreporting** [comment]
@chrislkeller Managed to standardize officeID for LAC/SOS sources, but we're still approaching the contests for Supreme Court differently. You're creating a unique contest for each Supreme Court justice but only one contest for each Court of Appeal district, even though they are similar yes/no contests. For LAC, I'm now handling the Supreme Court and Courts of Appeal the same way, lumping together all candidates under one contest. There's probably no right answer here, but we have to make a choice and stay consistent. I think it's probably a little neater to lump the judicial candidates into the larger contests (i.e. Supreme Court, Court of Appeals 1, 2, etc), even though they're not actually competing against each other. But it may be more accurate to break them out into separate contests, so it's clearer that these contests are not competitive. This latter approach, however, requires a little extra refactoring on both SoS and LAC. Let's talk Tuesday.

**Comment by chrislkeller** [comment]
For the most part looks good, though we're still running into the collision for races at the state level.

Running the import gives me...
- los-angeles-county-state-assembly-district-43
- state-assembly-district-43

...which are the same office but from different sources...

I think we're in the clear for Tuesday, but let's allow you and I to rethink the office thing like we have talked about.
