### ISSUE TITLE
Understand LAC Nov. 8 election night workflow and available data

### ISSUE THREAD

**Issue by chrislkeller** [SCPR/kpcc_backroom_handshakes#34]
- [x] Email Mike Sanchez about access
  - Test file can be found at: https://s3-us-west-1.amazonaws.com/kpcc-projects/0016nov16.ets
- [x] Understand any request criteria - headers and time of requests
- [x] Add the findings to the proper documentation
- [x] Find out what the “crossover ballot” nonpartisan contest is on p. 007
  - This data is available in the .ets file but we are not scraping or importing. Can be checked manually for now.

**Comment by frankreporting** [comment]
Aren't these all just items we addressed in the June primary?

**Comment by chrislkeller** [comment]
@frankreporting: each election will bring changes we need to understand, and with those **to do** items, hence the need to know what those items are.
